package com.huidu.farmersdelight.loot;

import com.huidu.farmersdelight.FarmersDelightPlugin;
import com.huidu.farmersdelight.i18n.I18n;
import com.huidu.farmersdelight.util.DatapackSupport;
import org.bukkit.Bukkit;
import org.bukkit.World;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.world.WorldLoadEvent;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Enumeration;
import java.util.Set;
import java.util.TreeSet;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

public final class LootDatapackInstaller implements Listener {

    private static final String DATAPACK_NAME = "farmersdelight";
    private static final String RESOURCE_PREFIX = "datapack/loot/";
    private static final String APPEND_PREFIX = "datapack/loot-append/chests/";
    private static final String VANILLA_CHEST_PREFIX = "data/minecraft/loot_table/chests/";
    private static final String VANILLA_PROBE = VANILLA_CHEST_PREFIX + "simple_dungeon.json";

    private final FarmersDelightPlugin plugin;
    private final boolean installEnabled;

    public LootDatapackInstaller(FarmersDelightPlugin plugin) {
        this.plugin = plugin;
        this.installEnabled = plugin.getConfig().getBoolean("loot-injection.install-datapack", true);
    }

    public void installToAllWorlds() {
        if (!installEnabled) {
            I18n.logInfo("loot_datapack_disabled");
            return;
        }
        var worlds = Bukkit.getWorlds();
        if (worlds.isEmpty()) {
            I18n.logWarning("loot_datapack_no_worlds");
            return;
        }
        int installed = 0;
        for (World world : worlds) {
            if (plugin.isDatapackWorldAllowed(world)) {
                continue;
            }
            if (installToWorld(world)) installed++;
        }
        if (installed > 0) {
            printRestartBanner(installed);
        }
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onWorldLoad(WorldLoadEvent event) {
        if (plugin.isDatapackWorldAllowed(event.getWorld())) {
            return;
        }
        // Cover newly-created / runtime-loaded worlds (e.g. Multiverse) — same idempotent install path.
        // A world that actually receives files here needs the same restart notice the startup path prints:
        // the per-world write itself only reaches the startup detail channel, so without this banner an
        // install into a runtime-created world would leave no console trace and the operator would never
        // learn the loot injections are not live yet.
        if (installEnabled && installToWorld(event.getWorld())) {
            printRestartBanner(1);
        }
    }

    private void printRestartBanner(int worlds) {
        plugin.getLogger().warning("==================================================================");
        plugin.getLogger().warning(" Installed FarmersDelight loot datapack into " + worlds + " world(s).");
        plugin.getLogger().warning(" RESTART the server (or run /reload) for the loot injections to");
        plugin.getLogger().warning(" take effect. Custom items in vanilla chests / mob drops / grass");
        plugin.getLogger().warning(" will not appear until the datapack is loaded by vanilla.");
        plugin.getLogger().warning("==================================================================");
    }

    // Installs the datapack into one world. Static resources (pack.mcmeta) are copied only when
    // missing. Chest loot tables are generated by merging the current vanilla table read from the
    // running server jar with the FD append pools (and any addon injections), so vanilla entries
    // (music discs and anything newer server versions add) are always preserved. A merged table is
    // written only when its content differs from what is already on disk, so a plugin reload never
    // rewrites unchanged files and does not disturb running worlds.
    private boolean installToWorld(World world) {
        Path datapackDir = DatapackSupport.worldRoot(world).resolve("datapacks").resolve(DATAPACK_NAME);
        boolean debug = plugin.isDebugEnabled("startup");
        Path serverJar = findServerJar();
        if (serverJar == null) {
            plugin.getLogger().warning("FarmersDelight loot datapack: could not locate the server jar to read vanilla loot tables; skipping install");
            return false;
        }
        try {
            Files.createDirectories(datapackDir);
            int count = 0;
            int skipped = 0;
            try (JarFile ownJar = DatapackSupport.openPluginJar(plugin.getClass())) {
                // Static resources (pack.mcmeta): add-only, never overwrite a file the admin edited.
                Enumeration<JarEntry> entries = ownJar.entries();
                while (entries.hasMoreElements()) {
                    JarEntry entry = entries.nextElement();
                    if (entry.isDirectory()) continue;
                    String name = entry.getName();
                    if (!name.startsWith(RESOURCE_PREFIX)) continue;
                    String relative = name.substring(RESOURCE_PREFIX.length());
                    Path dest = datapackDir.resolve(relative);
                    if (Files.exists(dest)) {
                        skipped++;
                        if (debug) I18n.logInfo("loot_datapack_debug_skipped", "path", relative);
                        continue;
                    }
                    if (debug) I18n.logInfo("loot_datapack_debug_added", "path", relative);
                    DatapackSupport.copyFromJar(ownJar, entry, dest);
                    count++;
                }
                // Chest loot tables: vanilla pools merged with the FD append pools plus any addon
                // injections (FarmersDelightLootInjections), idempotent write. Addon tables that are
                // not among the bundled append files are generated the same way.
                try (JarFile vanillaJar = new JarFile(serverJar.toFile())) {
                    LootInjectionRegistry injections = plugin.getLootInjections();
                    Set<String> tables = new TreeSet<>();
                    Enumeration<JarEntry> appends = ownJar.entries();
                    while (appends.hasMoreElements()) {
                        JarEntry entry = appends.nextElement();
                        if (entry.isDirectory()) continue;
                        String name = entry.getName();
                        if (!name.startsWith(APPEND_PREFIX)) continue;
                        tables.add(name.substring(APPEND_PREFIX.length()));
                    }
                    if (injections != null) {
                        tables.addAll(injections.tables());
                    }
                    for (String relative : tables) {
                        String vanillaJson = DatapackSupport.readJarEntry(vanillaJar, VANILLA_CHEST_PREFIX + relative);
                        if (vanillaJson == null) {
                            plugin.getLogger().warning("FarmersDelight loot datapack: server jar has no vanilla table " + VANILLA_CHEST_PREFIX + relative + "; skipping");
                            continue;
                        }
                        // Combine the bundled FD append pools with any addon-injected pools into one
                        // append document, then filter deleted CE items and merge with the vanilla table.
                        String appendJson = "{\"pools\":[]}";
                        String bundled = DatapackSupport.readJarEntry(ownJar, APPEND_PREFIX + relative);
                        if (bundled != null) {
                            appendJson = LootTableMerger.merge(appendJson, bundled);
                        }
                        String addonPools = injections == null ? null : injections.poolsJson(relative);
                        if (addonPools != null) {
                            appendJson = LootTableMerger.merge(appendJson, addonPools);
                        }
                        LootTableMerger.FilterResult filtered =
                                LootTableMerger.filterMissingCeItems(appendJson, plugin::isCeItemPresent);
                        if (!filtered.removedItemIds().isEmpty()) {
                            plugin.getLogger().info("FarmersDelight loot datapack: removed "
                                    + filtered.removedItemIds().size() + " entry(ies) for deleted CraftEngine item(s) in "
                                    + relative + ": " + String.join(", ", filtered.removedItemIds()));
                        }
                        String merged = LootTableMerger.merge(vanillaJson, filtered.json());
                        Path dest = datapackDir.resolve("data/minecraft/loot_table/chests/" + relative);
                        if (DatapackSupport.writeIfChanged(dest, merged)) {
                            count++;
                            if (debug) I18n.logInfo("loot_datapack_debug_added", "path", "chests/" + relative);
                        } else {
                            skipped++;
                            if (debug) I18n.logInfo("loot_datapack_debug_skipped", "path", "chests/" + relative);
                        }
                    }
                }
            }
            if (debug) {
                I18n.logInfo("loot_datapack_debug_summary", "count", count, "skipped", skipped, "dir", datapackDir.toString());
            }
            // Only a call that wrote at least one file counts as an install: the restart banner is about
            // datapack content the running server has not loaded yet, which is exactly this case. A boot
            // where every bundled file was already on disk changed nothing and must stay silent.
            return count > 0;
        } catch (IOException e) {
            I18n.logWarning("loot_datapack_install_failed", "world", world.getName(), "error", e.getMessage());
            return false;
        }
    }

    // Locates the running server jar on the class path by probing for the vanilla chest loot data.
    // The jar embeds the packed resources, so the current server version's tables are read verbatim.
    private static Path findServerJar() {
        // Standalone launchers put the server jar on the classpath.
        String classPath = System.getProperty("java.class.path", "");
        for (String part : classPath.split(java.io.File.pathSeparator)) {
            String path = part.trim();
            if (!path.isEmpty() && path.endsWith(".jar")) {
                Path jar = probeJar(java.nio.file.Paths.get(path));
                if (jar != null) {
                    return jar;
                }
            }
        }
        // Paperclip keeps only the launcher on the classpath and extracts the real server (with the vanilla
        // loot tables) under versions/ and the raw Mojang jar under cache/; scan those.
        for (String dir : new String[]{"versions", "cache", "bundler/versions"}) {
            Path found = scanForVanillaJar(java.nio.file.Paths.get(dir));
            if (found != null) {
                return found;
            }
        }
        return null;
    }

    private static Path probeJar(Path path) {
        try (JarFile jar = new JarFile(path.toFile())) {
            if (jar.getJarEntry(VANILLA_PROBE) != null) {
                return path;
            }
        } catch (IOException ignored) {
        }
        return null;
    }

    private static Path scanForVanillaJar(Path dir) {
        if (!Files.isDirectory(dir)) {
            return null;
        }
        try (var stream = Files.walk(dir, 3)) {
            return stream
                    .filter(p -> p.getFileName().toString().endsWith(".jar"))
                    .map(LootDatapackInstaller::probeJar)
                    .filter(java.util.Objects::nonNull)
                    .findFirst()
                    .orElse(null);
        } catch (IOException ignored) {
            return null;
        }
    }
}
