name: FarmersDelight
version: ${version}
main: com.huidu.farmersdelight.FarmersDelightPlugin
api-version: '1.21'
folia-supported: true
depend: [CraftEngine]
softdepend: [AuraSkills, UltimateAdvancementAPI, PlaceholderAPI, WorldGuard, GriefPrevention, Lands, Towny, Residence, PlotSquared, Factions, HuskClaims, HuskTowns, BentoBox, SuperiorSkyblock2, IridiumSkyblock, GriefDefender, Kingdoms, CrashClaim, RedProtect, Landlord, uSkyBlock, XClaim, UltimateClaims, UltimateClans, PreciousStones, Dominion, FabledSkyBlock, NoBuildPlus, Protect]
authors:
  - HuiDu_OwO
description: CraftEngine Farmer's Delight Addon
commands:
  farmersdelight:
    description: Main FarmersDelight command
    usage: /farmersdelight [recipe|reload|help]
    aliases: [fd]
    permission: farmersdelight.command
permissions:
  farmersdelight.command:
    description: Allow to use main command
    default: true
  farmersdelight.command.recipe:
    description: Allow to check the recipe
    default: true
  farmersdelight.command.recipe.discovery:
    description: Allow to unlock the recipe
    default: op
  farmersdelight.use.cooking_pot:
    description: Allow to use the Cooking Pot
    default: true
  farmersdelight.use.stove:
    description: Allow to use the Stove
    default: true
  farmersdelight.use.skillet:
    description: Allow to use the Skillet
    default: true
  farmersdelight.use.cutting_board:
    description: Allow to use the Cutting Board
    default: true
  farmersdelight.admin:
    description: Admin permissions
    default: op
  farmersdelight.*:
    description: All the FarmersDelight Plugin's permissions
    default: op
    children:
      farmersdelight.command: true
      farmersdelight.command.recipe: true
      farmersdelight.command.recipe.discovery: true
      farmersdelight.use.cooking_pot: true
      farmersdelight.use.stove: true
      farmersdelight.use.skillet: true
      farmersdelight.use.cutting_board: true
      farmersdelight.admin: true
